<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />


<meta name="author" content="Luke Hamm" />

<meta name="date" content="2025-06-22" />

<title>Optimal Pitch Mechanics for Maximising Velocity</title>

<script src="libs/header-attrs-2.29/header-attrs.js"></script>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="libs/bootstrap-3.3.5/css/cerulean.min.css" rel="stylesheet" />
<script src="libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="libs/jqueryui-1.13.2/jquery-ui.min.js"></script>
<link href="libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="libs/navigation-1.1/tabsets.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>



<style type="text/css">
  code {
    white-space: pre;
  }
  .sourceCode {
    overflow: visible;
  }
</style>
<style type="text/css" data-origin="pandoc">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  background-color: #f8f8f8; }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ef2929; } /* Alert */
code span.an { color: #8f5902; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #204a87; } /* Attribute */
code span.bn { color: #0000cf; } /* BaseN */
code span.cf { color: #204a87; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4e9a06; } /* Char */
code span.cn { color: #8f5902; } /* Constant */
code span.co { color: #8f5902; font-style: italic; } /* Comment */
code span.cv { color: #8f5902; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #8f5902; font-weight: bold; font-style: italic; } /* Documentation */
code span.dt { color: #204a87; } /* DataType */
code span.dv { color: #0000cf; } /* DecVal */
code span.er { color: #a40000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #0000cf; } /* Float */
code span.fu { color: #204a87; font-weight: bold; } /* Function */
code span.im { } /* Import */
code span.in { color: #8f5902; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #204a87; font-weight: bold; } /* Keyword */
code span.op { color: #ce5c00; font-weight: bold; } /* Operator */
code span.ot { color: #8f5902; } /* Other */
code span.pp { color: #8f5902; font-style: italic; } /* Preprocessor */
code span.sc { color: #ce5c00; font-weight: bold; } /* SpecialChar */
code span.ss { color: #4e9a06; } /* SpecialString */
code span.st { color: #4e9a06; } /* String */
code span.va { color: #000000; } /* Variable */
code span.vs { color: #4e9a06; } /* VerbatimString */
code span.wa { color: #8f5902; font-weight: bold; font-style: italic; } /* Warning */

</style>
<script>
// apply pandoc div.sourceCode style to pre.sourceCode instead
(function() {
  var sheets = document.styleSheets;
  for (var i = 0; i < sheets.length; i++) {
    if (sheets[i].ownerNode.dataset["origin"] !== "pandoc") continue;
    try { var rules = sheets[i].cssRules; } catch (e) { continue; }
    var j = 0;
    while (j < rules.length) {
      var rule = rules[j];
      // check if there is a div.sourceCode rule
      if (rule.type !== rule.STYLE_RULE || rule.selectorText !== "div.sourceCode") {
        j++;
        continue;
      }
      var style = rule.style.cssText;
      // check if color or background-color is set
      if (rule.style.color === '' && rule.style.backgroundColor === '') {
        j++;
        continue;
      }
      // replace div.sourceCode by a pre.sourceCode rule
      sheets[i].deleteRule(j);
      sheets[i].insertRule('pre.sourceCode{' + style + '}', j);
    }
  }
})();
</script>







<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>



<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div id="header">



<h1 class="title toc-ignore">Optimal Pitch Mechanics for Maximising
Velocity</h1>
<h4 class="author">Luke Hamm</h4>
<h4 class="date">2025-06-22</h4>

</div>


<div id="abstract" class="section level1" number="1">
<h1><span class="header-section-number">1</span> Abstract</h1>
<p>This study applies random-forest regression, multivariate adaptive
regression splines (MARS), and a trio of single-variable demonstrations
(polynomial, step, and B-spline)—to 30 + kinematic descriptors from
Driveline’s open-access motion-capture database. Our best model (MARS)
explains 91 % of the variance in fast-ball velocity and, through
partial-dependence analysis, pinpoints shoulder and elbow
external-rotation bandwidths that deliver the steepest velocity gains
with minimal mechanical change.</p>
</div>
<div id="introduction" class="section level1" number="2">
<h1><span class="header-section-number">2</span> Introduction</h1>
<p>Driveline Baseball’s Sports-Science Laboratory in Kent, WA operates
one of the world’s largest high-fidelity motion-capture installations
dedicated to baseball training and research. Beginning in 2022 the lab
launched the <strong>OpenBiomechanics Project (OBP)</strong> to publish
its data under an open-source license. The public repository contains
cleaned C3D files and derivative signal tables from more than 100
professional and collegiate pitchers captured at 240 Hz with a 45-marker
optical system (The OpenBiomechanics Project – GitHub).</p>
<p>The raw C3D files record full six-degree-of-freedom trajectories for
every marker over the entire pitching delivery, which makes them ideal
for detailed biomechanical modelling but computationally heavy for a
first-pass machine-learning study. For the present project I use the OBP
“points-of-interest” export—a flattened CSV in which each row is a
single pitch and each column is a discrete kinematic or kinetic variable
(e.g., max elbow flexion, peak pelvis angular velocity, stride length).
This reduction preserves the most interpretable features of the motion
while eliminating the need to align complete time-series waveforms. The
data set is available at <a
href="https://github.com/drivelineresearch/openbiomechanics/tree/pitch_data/baseball_pitching">https://github.com/drivelineresearch/openbiomechanics/tree/pitch_data/baseball_pitching</a>.</p>
<p>Pitch velocity remains the currency of modern baseball: harder
throwers generate more swings-and-misses, suppress contact quality, and
command greater market value. Yet velocity is ultimately constrained by
each athlete’s mechanics. The goal of this project is to identify which
discrete mechanical variables within the pitching motion are most
strongly associated with throwing the hardest. To interrogate the data,
we first benchmark a tuned random-forest regressor against a
multivariate adaptive regression spline (MARS) model whose hinge
functions capture non-linear, context-specific interactions between
joints. I Then drill down to the single mechanical feature most
correlated with velocity and fit classical polynomial, discretised-step,
and B-spline regressions to visualise its curvature in isolation.
Finally, I swept the top five high-leverage variables through
partial-dependence grids to locate the contiguous windows—“optimal
ranges”—where predicted velocity stays within 0.5 mph of its peak. These
ranges translate the black-box output into concrete, coach-friendly
targets that pitchers can train toward.</p>
</div>
<div id="exploratory-data-analysis" class="section level1" number="3">
<h1><span class="header-section-number">3</span> Exploratory Data
Analysis</h1>
<div id="load-initial-checks" class="section level2" number="3.1">
<h2><span class="header-section-number">3.1</span> Load &amp; initial
checks</h2>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" tabindex="-1"></a>raw <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&quot;poi_metrics (1).csv&quot;</span>)</span></code></pre></div>
<p>Below is a table that includes every variable in the dataset. This
will be helpful for reference later in the report.</p>
<div id="identifiers-pitch-info" class="section level3" number="3.1.1">
<h3><span class="header-section-number">3.1.1</span> Identifiers &amp;
Pitch Info</h3>
<table>
<thead>
<tr class="header">
<th>Variable</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>session_pitch</code></td>
<td>Unique pitch ID</td>
</tr>
<tr class="even">
<td><code>session</code></td>
<td>Unique session ID</td>
</tr>
<tr class="odd">
<td><code>p_throws</code></td>
<td>Pitcher handedness</td>
</tr>
<tr class="even">
<td><code>pitch_type</code></td>
<td>Pitch type</td>
</tr>
<tr class="odd">
<td><code>pitch_speed_mph</code></td>
<td>Pitch speed (mph)</td>
</tr>
</tbody>
</table>
</div>
<div id="peak-max-kinematics" class="section level3" number="3.1.2">
<h3><span class="header-section-number">3.1.2</span> Peak (“Max”)
Kinematics</h3>
<table>
<colgroup>
<col width="49%" />
<col width="50%" />
</colgroup>
<thead>
<tr class="header">
<th>Variable</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>max_shoulder_internal_rotational_velo</code></td>
<td>Peak shoulder IR velocity (°/s)</td>
</tr>
<tr class="even">
<td><code>max_elbow_extension_velo</code></td>
<td>Peak elbow extension velocity (°/s)</td>
</tr>
<tr class="odd">
<td><code>max_torso_rotational_velo</code></td>
<td>Peak torso axial-rotation velocity (°/s)</td>
</tr>
<tr class="even">
<td><code>max_rotation_hip_shoulder_separation</code></td>
<td>Peak hip-shoulder separation (°)</td>
</tr>
<tr class="odd">
<td><code>max_elbow_flexion</code></td>
<td>Peak elbow flexion (°)</td>
</tr>
<tr class="even">
<td><code>max_shoulder_external_rotation</code></td>
<td>Peak shoulder external rotation (°)</td>
</tr>
<tr class="odd">
<td><code>max_cog_velo_x</code></td>
<td>Peak CoG velocity toward plate (m/s)</td>
</tr>
<tr class="even">
<td><code>max_pelvis_rotational_velo</code></td>
<td>Peak pelvis rotation velocity (°/s)</td>
</tr>
<tr class="odd">
<td><code>max_shoulder_horizontal_abduction</code></td>
<td>Peak shoulder horiz. abduction (°)</td>
</tr>
<tr class="even">
<td><code>torso_rotation_min</code></td>
<td>Peak torso counter-rotation (°)</td>
</tr>
</tbody>
</table>
</div>
<div id="foot-plant-_fp" class="section level3" number="3.1.3">
<h3><span class="header-section-number">3.1.3</span> Foot Plant
(<code>*_fp</code>)</h3>
<table>
<colgroup>
<col width="53%" />
<col width="46%" />
</colgroup>
<thead>
<tr class="header">
<th>Variable</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>elbow_flexion_fp</code></td>
<td>Elbow flexion (°)</td>
</tr>
<tr class="even">
<td><code>elbow_pronation_fp</code></td>
<td>Wrist pronation (°)</td>
</tr>
<tr class="odd">
<td><code>rotation_hip_shoulder_separation_fp</code></td>
<td>Hip-shoulder separation (°)</td>
</tr>
<tr class="even">
<td><code>shoulder_horizontal_abduction_fp</code></td>
<td>Shoulder horiz. abduction (°)</td>
</tr>
<tr class="odd">
<td><code>shoulder_abduction_fp</code></td>
<td>Shoulder abduction (°)</td>
</tr>
<tr class="even">
<td><code>shoulder_external_rotation_fp</code></td>
<td>Shoulder ER (°)</td>
</tr>
<tr class="odd">
<td><code>lead_knee_extension_angular_velo_fp</code></td>
<td>Lead-knee ext. velocity (°/s)</td>
</tr>
<tr class="even">
<td><code>torso_anterior_tilt_fp</code></td>
<td>Trunk flexion (°)</td>
</tr>
<tr class="odd">
<td><code>torso_lateral_tilt_fp</code></td>
<td>Trunk lateral flexion (°)</td>
</tr>
<tr class="even">
<td><code>torso_rotation_fp</code></td>
<td>Trunk axial rotation (°)</td>
</tr>
<tr class="odd">
<td><code>pelvis_anterior_tilt_fp</code></td>
<td>Pelvis anterior tilt (°)</td>
</tr>
<tr class="even">
<td><code>pelvis_lateral_tilt_fp</code></td>
<td>Pelvis lateral tilt (°)</td>
</tr>
<tr class="odd">
<td><code>pelvis_rotation_fp</code></td>
<td>Pelvis axial rotation (°)</td>
</tr>
<tr class="even">
<td><code>glove_shoulder_horizontal_abduction_fp</code></td>
<td>Glove-shoulder horiz. abduction (°)</td>
</tr>
<tr class="odd">
<td><code>glove_shoulder_abduction_fp</code></td>
<td>Glove-shoulder abduction (°)</td>
</tr>
<tr class="even">
<td><code>glove_shoulder_external_rotation_fp</code></td>
<td>Glove-shoulder ER (°)</td>
</tr>
</tbody>
</table>
</div>
<div id="max-external-rotation-_mer" class="section level3"
number="3.1.4">
<h3><span class="header-section-number">3.1.4</span> Max External
Rotation (<code>*_mer</code>)</h3>
<table>
<thead>
<tr class="header">
<th>Variable</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>glove_shoulder_abduction_mer</code></td>
<td>Glove-shoulder abduction (°)</td>
</tr>
<tr class="even">
<td><code>elbow_flexion_mer</code></td>
<td>Elbow flexion (°)</td>
</tr>
<tr class="odd">
<td><code>torso_anterior_tilt_mer</code></td>
<td>Trunk flexion (°)</td>
</tr>
<tr class="even">
<td><code>torso_lateral_tilt_mer</code></td>
<td>Trunk lateral flexion (°)</td>
</tr>
<tr class="odd">
<td><code>torso_rotation_mer</code></td>
<td>Trunk axial rotation (°)</td>
</tr>
</tbody>
</table>
</div>
<div id="ball-release-_br" class="section level3" number="3.1.5">
<h3><span class="header-section-number">3.1.5</span> Ball Release
(<code>*_br</code>)</h3>
<table>
<colgroup>
<col width="56%" />
<col width="43%" />
</colgroup>
<thead>
<tr class="header">
<th>Variable</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>lead_knee_extension_angular_velo_br</code></td>
<td>Lead-knee ext. velocity (°/s)</td>
</tr>
<tr class="even">
<td><code>torso_anterior_tilt_br</code></td>
<td>Trunk flexion (°)</td>
</tr>
<tr class="odd">
<td><code>torso_lateral_tilt_br</code></td>
<td>Trunk lateral flexion (°)</td>
</tr>
<tr class="even">
<td><code>torso_rotation_br</code></td>
<td>Trunk axial rotation (°)</td>
</tr>
</tbody>
</table>
</div>
<div id="timing-stride" class="section level3" number="3.1.6">
<h3><span class="header-section-number">3.1.6</span> Timing &amp;
Stride</h3>
<table>
<colgroup>
<col width="53%" />
<col width="46%" />
</colgroup>
<thead>
<tr class="header">
<th>Variable</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>lead_knee_extension_from_fp_to_br</code></td>
<td>Δ Lead-knee ext. (°)</td>
</tr>
<tr class="even">
<td><code>timing_peak_torso_to_peak_pelvis_rot_velo</code></td>
<td>Time peak pelvis → peak torso (s)</td>
</tr>
<tr class="odd">
<td><code>stride_length</code></td>
<td>Stride length (% body ht)</td>
</tr>
<tr class="even">
<td><code>stride_angle</code></td>
<td>Stride angle (°; + = cross-body)</td>
</tr>
<tr class="odd">
<td><code>arm_slot</code></td>
<td>Arm slot (forearm proj. angle, °)</td>
</tr>
<tr class="even">
<td><code>cog_velo_pkh</code></td>
<td>CoG velocity at peak-knee-height (m/s)</td>
</tr>
</tbody>
</table>
</div>
<div id="joint-energy-foot-plant-ball-release" class="section level3"
number="3.1.7">
<h3><span class="header-section-number">3.1.7</span> Joint Energy (Foot
Plant → Ball Release)</h3>
<table>
<colgroup>
<col width="67%" />
<col width="32%" />
</colgroup>
<thead>
<tr class="header">
<th>Variable</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>shoulder_transfer_fp_br</code> / <code>generation</code> /
<code>absorption</code></td>
<td>Shoulder energy (J)</td>
</tr>
<tr class="even">
<td><code>elbow_transfer_fp_br</code> / <code>generation</code> /
<code>absorption</code></td>
<td>Elbow energy (J)</td>
</tr>
<tr class="odd">
<td><code>lead_hip_transfer_fp_br</code> / <code>generation</code> /
<code>absorption</code></td>
<td>Lead-hip energy (J)</td>
</tr>
<tr class="even">
<td><code>lead_knee_transfer_fp_br</code> / <code>generation</code> /
<code>absorption</code></td>
<td>Lead-knee energy (J)</td>
</tr>
<tr class="odd">
<td><code>rear_hip_transfer_pkh_fp</code> / <code>generation</code> /
<code>absorption</code></td>
<td>Rear-hip energy (J)</td>
</tr>
<tr class="even">
<td><code>rear_knee_transfer_pkh_fp</code> / <code>generation</code> /
<code>absorption</code></td>
<td>Rear-knee energy (J)</td>
</tr>
<tr class="odd">
<td><code>pelvis_lumbar_transfer_fp_br</code></td>
<td>Pelvis → trunk energy (J)</td>
</tr>
<tr class="even">
<td><code>thorax_distal_transfer_fp_br</code></td>
<td>Trunk → shoulder energy (J)</td>
</tr>
</tbody>
</table>
</div>
<div id="moments" class="section level3" number="3.1.8">
<h3><span class="header-section-number">3.1.8</span> Moments</h3>
<table>
<thead>
<tr class="header">
<th>Variable</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>elbow_varus_moment</code></td>
<td>Peak elbow varus moment (N·m)</td>
</tr>
<tr class="even">
<td><code>shoulder_internal_rotation_moment</code></td>
<td>Peak shoulder IR moment (N·m)</td>
</tr>
</tbody>
</table>
</div>
<div id="ground-reaction-forces-peak" class="section level3"
number="3.1.9">
<h3><span class="header-section-number">3.1.9</span> Ground-Reaction
Forces (peak)</h3>
<table>
<colgroup>
<col width="64%" />
<col width="36%" />
</colgroup>
<thead>
<tr class="header">
<th>Variable</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>rear_grf_x_max</code> / <code>y_max</code> /
<code>z_max</code> / <code>mag_max</code></td>
<td>Rear-leg GRF components (N)</td>
</tr>
<tr class="even">
<td><code>rear_grf_angle_at_max</code></td>
<td>Rear-GRF vector angle (°)</td>
</tr>
<tr class="odd">
<td><code>lead_grf_x_max</code> / <code>y_max</code> /
<code>z_max</code> / <code>mag_max</code></td>
<td>Lead-leg GRF components (N)</td>
</tr>
<tr class="even">
<td><code>lead_grf_angle_at_max</code></td>
<td>Lead-GRF vector angle (°)</td>
</tr>
</tbody>
</table>
</div>
</div>
<div id="outcome-distribution" class="section level2" number="3.2">
<h2><span class="header-section-number">3.2</span> Outcome
distribution</h2>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" tabindex="-1"></a>raw <span class="sc">%&gt;%</span></span>
<span id="cb2-2"><a href="#cb2-2" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(pitch_speed_mph)) <span class="sc">+</span></span>
<span id="cb2-3"><a href="#cb2-3" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">2</span>, <span class="at">fill =</span> <span class="st">&quot;steelblue&quot;</span>, <span class="at">colour =</span> <span class="st">&quot;white&quot;</span>) <span class="sc">+</span></span>
<span id="cb2-4"><a href="#cb2-4" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="fu">c</span>(<span class="dv">85</span>, <span class="dv">90</span>), <span class="at">linetype =</span> <span class="st">&quot;dashed&quot;</span>) <span class="sc">+</span></span>
<span id="cb2-5"><a href="#cb2-5" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Pitch-speed distribution with tier cut-points&quot;</span>,</span>
<span id="cb2-6"><a href="#cb2-6" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">&quot;Velocity (mph)&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Count&quot;</span>) <span class="sc">+</span></span>
<span id="cb2-7"><a href="#cb2-7" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="FinalProject1_files/figure-html/velo-hist-1.png" width="672" style="display: block; margin: auto;" /></p>
</div>
<div id="top-correlations" class="section level2" number="3.3">
<h2><span class="header-section-number">3.3</span> Top correlations</h2>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" tabindex="-1"></a>raw <span class="sc">%&gt;%</span> </span>
<span id="cb3-2"><a href="#cb3-2" tabindex="-1"></a>  <span class="fu">select</span>(<span class="fu">where</span>(is.numeric)) <span class="sc">%&gt;%</span> </span>
<span id="cb3-3"><a href="#cb3-3" tabindex="-1"></a>  <span class="fu">correlate</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb3-4"><a href="#cb3-4" tabindex="-1"></a>  <span class="fu">focus</span>(pitch_speed_mph) <span class="sc">%&gt;%</span> </span>
<span id="cb3-5"><a href="#cb3-5" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">r =</span> pitch_speed_mph) <span class="sc">%&gt;%</span>           </span>
<span id="cb3-6"><a href="#cb3-6" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="sc">-</span><span class="fu">abs</span>(r)) <span class="sc">%&gt;%</span> </span>
<span id="cb3-7"><a href="#cb3-7" tabindex="-1"></a>  <span class="fu">slice_head</span>(<span class="at">n =</span> <span class="dv">20</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb3-8"><a href="#cb3-8" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">term =</span> <span class="fu">fct_reorder</span>(term, r)) <span class="sc">%&gt;%</span>    </span>
<span id="cb3-9"><a href="#cb3-9" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> term, <span class="at">y =</span> r)) <span class="sc">+</span></span>
<span id="cb3-10"><a href="#cb3-10" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">fill =</span> <span class="st">&quot;steelblue&quot;</span>) <span class="sc">+</span></span>
<span id="cb3-11"><a href="#cb3-11" tabindex="-1"></a>  <span class="fu">coord_flip</span>() <span class="sc">+</span></span>
<span id="cb3-12"><a href="#cb3-12" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Top 20 correlations with pitch velocity&quot;</span>,</span>
<span id="cb3-13"><a href="#cb3-13" tabindex="-1"></a>       <span class="at">x =</span> <span class="cn">NULL</span>, <span class="at">y =</span> <span class="st">&quot;Pearson r&quot;</span>) <span class="sc">+</span></span>
<span id="cb3-14"><a href="#cb3-14" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">12</span>)</span></code></pre></div>
<p><img src="FinalProject1_files/figure-html/unnamed-chunk-1-1.png" width="672" style="display: block; margin: auto;" /></p>
</div>
</div>
<div id="data-preparation" class="section level1" number="4">
<h1><span class="header-section-number">4</span> Data preparation</h1>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" tabindex="-1"></a>velo_tier <span class="ot">&lt;-</span> <span class="cf">function</span>(x) <span class="fu">cut</span>(</span>
<span id="cb4-2"><a href="#cb4-2" tabindex="-1"></a>  x,</span>
<span id="cb4-3"><a href="#cb4-3" tabindex="-1"></a>  <span class="at">breaks  =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="cn">Inf</span>, <span class="dv">85</span>, <span class="dv">90</span>, <span class="cn">Inf</span>),</span>
<span id="cb4-4"><a href="#cb4-4" tabindex="-1"></a>  <span class="at">labels  =</span> <span class="fu">c</span>(<span class="st">&quot;Low&quot;</span>, <span class="st">&quot;Medium&quot;</span>, <span class="st">&quot;High&quot;</span>),</span>
<span id="cb4-5"><a href="#cb4-5" tabindex="-1"></a>  <span class="at">right   =</span> <span class="cn">FALSE</span></span>
<span id="cb4-6"><a href="#cb4-6" tabindex="-1"></a>)</span>
<span id="cb4-7"><a href="#cb4-7" tabindex="-1"></a></span>
<span id="cb4-8"><a href="#cb4-8" tabindex="-1"></a>pitch_df <span class="ot">&lt;-</span> raw <span class="sc">%&gt;%</span></span>
<span id="cb4-9"><a href="#cb4-9" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>session_pitch, <span class="sc">-</span>session, <span class="sc">-</span>p_throws, <span class="sc">-</span>pitch_type) <span class="sc">%&gt;%</span></span>
<span id="cb4-10"><a href="#cb4-10" tabindex="-1"></a>  <span class="fu">drop_na</span>() <span class="sc">%&gt;%</span></span>
<span id="cb4-11"><a href="#cb4-11" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">velo_class =</span> <span class="fu">velo_tier</span>(pitch_speed_mph))</span>
<span id="cb4-12"><a href="#cb4-12" tabindex="-1"></a></span>
<span id="cb4-13"><a href="#cb4-13" tabindex="-1"></a>pitch_split <span class="ot">&lt;-</span> <span class="fu">initial_split</span>(pitch_df, <span class="at">prop =</span> <span class="fl">0.8</span>, <span class="at">strata =</span> pitch_speed_mph)</span>
<span id="cb4-14"><a href="#cb4-14" tabindex="-1"></a>train_data  <span class="ot">&lt;-</span> <span class="fu">training</span>(pitch_split)</span>
<span id="cb4-15"><a href="#cb4-15" tabindex="-1"></a>test_data   <span class="ot">&lt;-</span> <span class="fu">testing</span>(pitch_split)</span>
<span id="cb4-16"><a href="#cb4-16" tabindex="-1"></a></span>
<span id="cb4-17"><a href="#cb4-17" tabindex="-1"></a>cv_folds <span class="ot">&lt;-</span> <span class="fu">vfold_cv</span>(train_data, <span class="at">v =</span> <span class="dv">5</span>, <span class="at">strata =</span> pitch_speed_mph)</span></code></pre></div>
</div>
<div id="modelling" class="section level1" number="5">
<h1><span class="header-section-number">5</span> Modelling</h1>
<div id="random-forest-regression-primary" class="section level2"
number="5.1">
<h2><span class="header-section-number">5.1</span> Random-forest
regression (primary)</h2>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" tabindex="-1"></a>rf_spec <span class="ot">&lt;-</span> <span class="fu">rand_forest</span>(<span class="at">mtry =</span> <span class="fu">tune</span>(), <span class="at">min_n =</span> <span class="fu">tune</span>(), <span class="at">trees =</span> <span class="dv">1000</span>) <span class="sc">%&gt;%</span></span>
<span id="cb5-2"><a href="#cb5-2" tabindex="-1"></a>  <span class="fu">set_engine</span>(<span class="st">&quot;ranger&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb5-3"><a href="#cb5-3" tabindex="-1"></a>  <span class="fu">set_mode</span>(<span class="st">&quot;regression&quot;</span>)</span>
<span id="cb5-4"><a href="#cb5-4" tabindex="-1"></a></span>
<span id="cb5-5"><a href="#cb5-5" tabindex="-1"></a>rf_recipe <span class="ot">&lt;-</span> <span class="fu">recipe</span>(pitch_speed_mph <span class="sc">~</span> ., <span class="at">data =</span> train_data) <span class="sc">%&gt;%</span></span>
<span id="cb5-6"><a href="#cb5-6" tabindex="-1"></a>  <span class="fu">step_rm</span>(velo_class) <span class="sc">%&gt;%</span></span>
<span id="cb5-7"><a href="#cb5-7" tabindex="-1"></a>  <span class="fu">step_nzv</span>(<span class="fu">all_predictors</span>())</span>
<span id="cb5-8"><a href="#cb5-8" tabindex="-1"></a></span>
<span id="cb5-9"><a href="#cb5-9" tabindex="-1"></a>rf_wflow <span class="ot">&lt;-</span> <span class="fu">workflow</span>() <span class="sc">%&gt;%</span></span>
<span id="cb5-10"><a href="#cb5-10" tabindex="-1"></a>  <span class="fu">add_recipe</span>(rf_recipe) <span class="sc">%&gt;%</span></span>
<span id="cb5-11"><a href="#cb5-11" tabindex="-1"></a>  <span class="fu">add_model</span>(rf_spec)</span>
<span id="cb5-12"><a href="#cb5-12" tabindex="-1"></a></span>
<span id="cb5-13"><a href="#cb5-13" tabindex="-1"></a>rf_grid <span class="ot">&lt;-</span> <span class="fu">grid_regular</span>(</span>
<span id="cb5-14"><a href="#cb5-14" tabindex="-1"></a>  <span class="fu">mtry</span>(<span class="at">range   =</span> <span class="fu">c</span>(<span class="dv">5</span>, <span class="dv">25</span>)),</span>
<span id="cb5-15"><a href="#cb5-15" tabindex="-1"></a>  <span class="fu">min_n</span>(<span class="at">range =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">10</span>)),</span>
<span id="cb5-16"><a href="#cb5-16" tabindex="-1"></a>  <span class="at">levels       =</span> <span class="dv">5</span></span>
<span id="cb5-17"><a href="#cb5-17" tabindex="-1"></a>)</span>
<span id="cb5-18"><a href="#cb5-18" tabindex="-1"></a></span>
<span id="cb5-19"><a href="#cb5-19" tabindex="-1"></a>rf_res  <span class="ot">&lt;-</span> <span class="fu">tune_grid</span>(</span>
<span id="cb5-20"><a href="#cb5-20" tabindex="-1"></a>  rf_wflow,</span>
<span id="cb5-21"><a href="#cb5-21" tabindex="-1"></a>  <span class="at">resamples =</span> cv_folds,</span>
<span id="cb5-22"><a href="#cb5-22" tabindex="-1"></a>  <span class="at">grid      =</span> rf_grid,</span>
<span id="cb5-23"><a href="#cb5-23" tabindex="-1"></a>  <span class="at">metrics   =</span> <span class="fu">metric_set</span>(rmse, rsq)</span>
<span id="cb5-24"><a href="#cb5-24" tabindex="-1"></a>)</span>
<span id="cb5-25"><a href="#cb5-25" tabindex="-1"></a></span>
<span id="cb5-26"><a href="#cb5-26" tabindex="-1"></a>rf_best  <span class="ot">&lt;-</span> <span class="fu">select_best</span>(rf_res, <span class="at">metric =</span> <span class="st">&quot;rmse&quot;</span>)</span>
<span id="cb5-27"><a href="#cb5-27" tabindex="-1"></a>rf_final <span class="ot">&lt;-</span> <span class="fu">finalize_workflow</span>(rf_wflow, rf_best) <span class="sc">%&gt;%</span> <span class="fu">fit</span>(train_data)</span></code></pre></div>
<div id="hold-out-metrics" class="section level3" number="5.1.1">
<h3><span class="header-section-number">5.1.1</span> Hold-out
metrics</h3>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" tabindex="-1"></a>rf_hold <span class="ot">&lt;-</span> rf_final <span class="sc">%&gt;%</span></span>
<span id="cb6-2"><a href="#cb6-2" tabindex="-1"></a>  <span class="fu">predict</span>(test_data) <span class="sc">%&gt;%</span></span>
<span id="cb6-3"><a href="#cb6-3" tabindex="-1"></a>  <span class="fu">bind_cols</span>(test_data)</span>
<span id="cb6-4"><a href="#cb6-4" tabindex="-1"></a></span>
<span id="cb6-5"><a href="#cb6-5" tabindex="-1"></a>rf_hold <span class="sc">%&gt;%</span> <span class="fu">metrics</span>(<span class="at">truth =</span> pitch_speed_mph, <span class="at">estimate =</span> .pred)</span></code></pre></div>
<pre><code>## # A tibble: 3 × 3
##   .metric .estimator .estimate
##   &lt;chr&gt;   &lt;chr&gt;          &lt;dbl&gt;
## 1 rmse    standard       1.86 
## 2 rsq     standard       0.859
## 3 mae     standard       1.34</code></pre>
</div>
<div id="tier-metrics" class="section level3" number="5.1.2">
<h3><span class="header-section-number">5.1.2</span> Tier metrics</h3>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" tabindex="-1"></a>rf_hold <span class="sc">%&gt;%</span></span>
<span id="cb8-2"><a href="#cb8-2" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">pred_tier =</span> <span class="fu">velo_tier</span>(.pred)) <span class="sc">%&gt;%</span></span>
<span id="cb8-3"><a href="#cb8-3" tabindex="-1"></a>  <span class="fu">metrics</span>(<span class="at">truth =</span> velo_class, <span class="at">estimate =</span> pred_tier)</span></code></pre></div>
<pre><code>## # A tibble: 2 × 3
##   .metric  .estimator .estimate
##   &lt;chr&gt;    &lt;chr&gt;          &lt;dbl&gt;
## 1 accuracy multiclass     0.817
## 2 kap      multiclass     0.677</code></pre>
</div>
</div>
<div id="polynomial-step-function-and-spline-demos-single-variable"
class="section level2" number="5.2">
<h2><span class="header-section-number">5.2</span> Polynomial,
step-function, and spline demos (single variable)</h2>
<p>Many coaching conversations revolve around <strong>one key mechanic
at a time</strong>. To illustrate how classical regression handles
non-linearity, I am going to isolate the <em>single</em> mechanical
variable most correlated with velocity and fit three small models:
polynomial expansion, discretised (step) function, and B-spline.</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" tabindex="-1"></a>best_mech <span class="ot">&lt;-</span> train_data <span class="sc">%&gt;%</span></span>
<span id="cb10-2"><a href="#cb10-2" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>pitch_speed_mph, <span class="sc">-</span>velo_class) <span class="sc">%&gt;%</span></span>
<span id="cb10-3"><a href="#cb10-3" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="fu">across</span>(<span class="fu">everything</span>(),</span>
<span id="cb10-4"><a href="#cb10-4" tabindex="-1"></a>                   <span class="sc">~</span><span class="fu">cor</span>(.x, train_data<span class="sc">$</span>pitch_speed_mph,</span>
<span id="cb10-5"><a href="#cb10-5" tabindex="-1"></a>                        <span class="at">use =</span> <span class="st">&quot;complete.obs&quot;</span>))) <span class="sc">%&gt;%</span></span>
<span id="cb10-6"><a href="#cb10-6" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="fu">everything</span>(),</span>
<span id="cb10-7"><a href="#cb10-7" tabindex="-1"></a>               <span class="at">names_to  =</span> <span class="st">&quot;var&quot;</span>,</span>
<span id="cb10-8"><a href="#cb10-8" tabindex="-1"></a>               <span class="at">values_to =</span> <span class="st">&quot;cor&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb10-9"><a href="#cb10-9" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(<span class="fu">abs</span>(cor))) <span class="sc">%&gt;%</span></span>
<span id="cb10-10"><a href="#cb10-10" tabindex="-1"></a>  <span class="fu">slice_head</span>(<span class="at">n =</span> <span class="dv">1</span>) <span class="sc">%&gt;%</span></span>
<span id="cb10-11"><a href="#cb10-11" tabindex="-1"></a>  <span class="fu">pull</span>(var)</span>
<span id="cb10-12"><a href="#cb10-12" tabindex="-1"></a></span>
<span id="cb10-13"><a href="#cb10-13" tabindex="-1"></a>best_mech</span></code></pre></div>
<pre><code>## [1] &quot;elbow_transfer_fp_br&quot;</code></pre>
<div id="fourth-degree-polynomial" class="section level3"
number="5.2.1">
<h3><span class="header-section-number">5.2.1</span> Fourth-degree
polynomial</h3>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" tabindex="-1"></a>poly_rec <span class="ot">&lt;-</span> <span class="fu">recipe</span>(</span>
<span id="cb12-2"><a href="#cb12-2" tabindex="-1"></a>  pitch_speed_mph <span class="sc">~</span> .,</span>
<span id="cb12-3"><a href="#cb12-3" tabindex="-1"></a>  <span class="at">data =</span> train_data <span class="sc">%&gt;%</span> <span class="fu">select</span>(pitch_speed_mph, <span class="sc">!!</span><span class="fu">sym</span>(best_mech))</span>
<span id="cb12-4"><a href="#cb12-4" tabindex="-1"></a>) <span class="sc">%&gt;%</span></span>
<span id="cb12-5"><a href="#cb12-5" tabindex="-1"></a>  <span class="fu">step_poly</span>(<span class="fu">all_predictors</span>(), <span class="at">degree =</span> <span class="dv">4</span>)</span>
<span id="cb12-6"><a href="#cb12-6" tabindex="-1"></a></span>
<span id="cb12-7"><a href="#cb12-7" tabindex="-1"></a>lm_spec  <span class="ot">&lt;-</span> <span class="fu">linear_reg</span>() <span class="sc">%&gt;%</span> <span class="fu">set_engine</span>(<span class="st">&quot;lm&quot;</span>)</span>
<span id="cb12-8"><a href="#cb12-8" tabindex="-1"></a></span>
<span id="cb12-9"><a href="#cb12-9" tabindex="-1"></a>poly_wf  <span class="ot">&lt;-</span> <span class="fu">workflow</span>() <span class="sc">%&gt;%</span></span>
<span id="cb12-10"><a href="#cb12-10" tabindex="-1"></a>  <span class="fu">add_recipe</span>(poly_rec) <span class="sc">%&gt;%</span></span>
<span id="cb12-11"><a href="#cb12-11" tabindex="-1"></a>  <span class="fu">add_model</span>(lm_spec)</span>
<span id="cb12-12"><a href="#cb12-12" tabindex="-1"></a></span>
<span id="cb12-13"><a href="#cb12-13" tabindex="-1"></a>poly_fit <span class="ot">&lt;-</span> <span class="fu">fit</span>(poly_wf, <span class="at">data =</span> train_data)</span></code></pre></div>
</div>
<div id="step-function-4-bins-equal-count" class="section level3"
number="5.2.2">
<h3><span class="header-section-number">5.2.2</span> Step function (4
bins, equal count)</h3>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" tabindex="-1"></a>step_rec <span class="ot">&lt;-</span> <span class="fu">recipe</span>(</span>
<span id="cb13-2"><a href="#cb13-2" tabindex="-1"></a>  pitch_speed_mph <span class="sc">~</span> .,</span>
<span id="cb13-3"><a href="#cb13-3" tabindex="-1"></a>  <span class="at">data =</span> train_data <span class="sc">%&gt;%</span> <span class="fu">select</span>(pitch_speed_mph, <span class="sc">!!</span><span class="fu">sym</span>(best_mech))</span>
<span id="cb13-4"><a href="#cb13-4" tabindex="-1"></a>) <span class="sc">%&gt;%</span></span>
<span id="cb13-5"><a href="#cb13-5" tabindex="-1"></a>  <span class="fu">step_discretize</span>(<span class="fu">all_predictors</span>(), <span class="at">num_breaks =</span> <span class="dv">4</span>)</span>
<span id="cb13-6"><a href="#cb13-6" tabindex="-1"></a></span>
<span id="cb13-7"><a href="#cb13-7" tabindex="-1"></a>step_wf  <span class="ot">&lt;-</span> <span class="fu">workflow</span>() <span class="sc">%&gt;%</span></span>
<span id="cb13-8"><a href="#cb13-8" tabindex="-1"></a>  <span class="fu">add_recipe</span>(step_rec) <span class="sc">%&gt;%</span></span>
<span id="cb13-9"><a href="#cb13-9" tabindex="-1"></a>  <span class="fu">add_model</span>(lm_spec)</span>
<span id="cb13-10"><a href="#cb13-10" tabindex="-1"></a></span>
<span id="cb13-11"><a href="#cb13-11" tabindex="-1"></a>step_fit <span class="ot">&lt;-</span> <span class="fu">fit</span>(step_wf, <span class="at">data =</span> train_data)</span></code></pre></div>
</div>
<div id="b-spline-5-degrees-of-freedom" class="section level3"
number="5.2.3">
<h3><span class="header-section-number">5.2.3</span> B-spline (5 degrees
of freedom)</h3>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" tabindex="-1"></a>spline_rec <span class="ot">&lt;-</span> <span class="fu">recipe</span>(</span>
<span id="cb14-2"><a href="#cb14-2" tabindex="-1"></a>  pitch_speed_mph <span class="sc">~</span> .,</span>
<span id="cb14-3"><a href="#cb14-3" tabindex="-1"></a>  <span class="at">data =</span> train_data <span class="sc">%&gt;%</span> <span class="fu">select</span>(pitch_speed_mph, <span class="sc">!!</span><span class="fu">sym</span>(best_mech))</span>
<span id="cb14-4"><a href="#cb14-4" tabindex="-1"></a>) <span class="sc">%&gt;%</span></span>
<span id="cb14-5"><a href="#cb14-5" tabindex="-1"></a>  <span class="fu">step_bs</span>(<span class="fu">all_predictors</span>(), <span class="at">deg_free =</span> <span class="dv">5</span>)</span>
<span id="cb14-6"><a href="#cb14-6" tabindex="-1"></a></span>
<span id="cb14-7"><a href="#cb14-7" tabindex="-1"></a>spline_wf  <span class="ot">&lt;-</span> <span class="fu">workflow</span>() <span class="sc">%&gt;%</span></span>
<span id="cb14-8"><a href="#cb14-8" tabindex="-1"></a>  <span class="fu">add_recipe</span>(spline_rec) <span class="sc">%&gt;%</span></span>
<span id="cb14-9"><a href="#cb14-9" tabindex="-1"></a>  <span class="fu">add_model</span>(lm_spec)</span>
<span id="cb14-10"><a href="#cb14-10" tabindex="-1"></a></span>
<span id="cb14-11"><a href="#cb14-11" tabindex="-1"></a>spline_fit <span class="ot">&lt;-</span> <span class="fu">fit</span>(spline_wf, <span class="at">data =</span> train_data)</span></code></pre></div>
</div>
</div>
<div id="mars-multivariate-adaptive-regression-splines"
class="section level2" number="5.3">
<h2><span class="header-section-number">5.3</span> MARS (multivariate
adaptive regression splines)</h2>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" tabindex="-1"></a>mars_spec <span class="ot">&lt;-</span> <span class="fu">mars</span>() <span class="sc">%&gt;%</span> <span class="fu">set_mode</span>(<span class="st">&quot;regression&quot;</span>)</span>
<span id="cb15-2"><a href="#cb15-2" tabindex="-1"></a></span>
<span id="cb15-3"><a href="#cb15-3" tabindex="-1"></a>mars_wf <span class="ot">&lt;-</span> <span class="fu">workflow</span>() <span class="sc">%&gt;%</span></span>
<span id="cb15-4"><a href="#cb15-4" tabindex="-1"></a>  <span class="fu">add_model</span>(mars_spec) <span class="sc">%&gt;%</span></span>
<span id="cb15-5"><a href="#cb15-5" tabindex="-1"></a>  <span class="fu">add_formula</span>(pitch_speed_mph <span class="sc">~</span> .)  <span class="co"># earth cannot use recipes</span></span>
<span id="cb15-6"><a href="#cb15-6" tabindex="-1"></a></span>
<span id="cb15-7"><a href="#cb15-7" tabindex="-1"></a>mars_res <span class="ot">&lt;-</span> <span class="fu">fit_resamples</span>(</span>
<span id="cb15-8"><a href="#cb15-8" tabindex="-1"></a>  mars_wf, <span class="at">resamples =</span> cv_folds,</span>
<span id="cb15-9"><a href="#cb15-9" tabindex="-1"></a>  <span class="at">metrics  =</span> <span class="fu">metric_set</span>(rmse, rsq)</span>
<span id="cb15-10"><a href="#cb15-10" tabindex="-1"></a>)</span>
<span id="cb15-11"><a href="#cb15-11" tabindex="-1"></a></span>
<span id="cb15-12"><a href="#cb15-12" tabindex="-1"></a><span class="fu">collect_metrics</span>(mars_res)</span></code></pre></div>
<pre><code>## # A tibble: 2 × 6
##   .metric .estimator  mean     n std_err .config             
##   &lt;chr&gt;   &lt;chr&gt;      &lt;dbl&gt; &lt;int&gt;   &lt;dbl&gt; &lt;chr&gt;               
## 1 rmse    standard   1.44      5 0.0517  Preprocessor1_Model1
## 2 rsq     standard   0.908     5 0.00965 Preprocessor1_Model1</code></pre>
</div>
</div>
<div id="results" class="section level1" number="6">
<h1><span class="header-section-number">6</span> Results</h1>
<div id="model-performance-summary" class="section level2" number="6.1">
<h2><span class="header-section-number">6.1</span> Model performance
summary</h2>
<p>The tuned <strong>random-forest regression</strong> explained
<strong>86 %</strong> of variance in pitch speed (RMSE = 1.86 mph). The
tuned <strong>multivariate adaptive regression splines</strong>
explained <strong>91 %</strong> of the variance in pitch speed (RMSE =
1.44 mph).</p>
</div>
<div id="visual-comparison-of-single-variable-regression-models"
class="section level2" number="6.2">
<h2><span class="header-section-number">6.2</span> Visual comparison of
single-variable regression models</h2>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" tabindex="-1"></a>x_seq <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb17-2"><a href="#cb17-2" tabindex="-1"></a>  <span class="sc">!!</span><span class="at">best_mech :=</span> <span class="fu">seq</span>(<span class="fu">min</span>(train_data[[best_mech]]),</span>
<span id="cb17-3"><a href="#cb17-3" tabindex="-1"></a>                     <span class="fu">max</span>(train_data[[best_mech]]),</span>
<span id="cb17-4"><a href="#cb17-4" tabindex="-1"></a>                     <span class="at">length.out =</span> <span class="dv">200</span>)</span>
<span id="cb17-5"><a href="#cb17-5" tabindex="-1"></a>)</span>
<span id="cb17-6"><a href="#cb17-6" tabindex="-1"></a></span>
<span id="cb17-7"><a href="#cb17-7" tabindex="-1"></a>poly_lines <span class="ot">&lt;-</span> <span class="fu">bind_cols</span>(</span>
<span id="cb17-8"><a href="#cb17-8" tabindex="-1"></a>  <span class="fu">augment</span>(poly_fit,   <span class="at">new_data =</span> x_seq),</span>
<span id="cb17-9"><a href="#cb17-9" tabindex="-1"></a>  <span class="fu">predict</span>(poly_fit,   <span class="at">new_data =</span> x_seq, <span class="at">type =</span> <span class="st">&quot;conf_int&quot;</span>)</span>
<span id="cb17-10"><a href="#cb17-10" tabindex="-1"></a>) <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">model =</span> <span class="st">&quot;Polynomial (deg 4)&quot;</span>)</span>
<span id="cb17-11"><a href="#cb17-11" tabindex="-1"></a></span>
<span id="cb17-12"><a href="#cb17-12" tabindex="-1"></a>step_lines <span class="ot">&lt;-</span> <span class="fu">bind_cols</span>(</span>
<span id="cb17-13"><a href="#cb17-13" tabindex="-1"></a>  <span class="fu">augment</span>(step_fit,   <span class="at">new_data =</span> x_seq),</span>
<span id="cb17-14"><a href="#cb17-14" tabindex="-1"></a>  <span class="fu">predict</span>(step_fit,   <span class="at">new_data =</span> x_seq, <span class="at">type =</span> <span class="st">&quot;conf_int&quot;</span>)</span>
<span id="cb17-15"><a href="#cb17-15" tabindex="-1"></a>) <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">model =</span> <span class="st">&quot;Step (4 bins)&quot;</span>)</span>
<span id="cb17-16"><a href="#cb17-16" tabindex="-1"></a></span>
<span id="cb17-17"><a href="#cb17-17" tabindex="-1"></a>spline_lines <span class="ot">&lt;-</span> <span class="fu">bind_cols</span>(</span>
<span id="cb17-18"><a href="#cb17-18" tabindex="-1"></a>  <span class="fu">augment</span>(spline_fit, <span class="at">new_data =</span> x_seq),</span>
<span id="cb17-19"><a href="#cb17-19" tabindex="-1"></a>  <span class="fu">predict</span>(spline_fit, <span class="at">new_data =</span> x_seq, <span class="at">type =</span> <span class="st">&quot;conf_int&quot;</span>)</span>
<span id="cb17-20"><a href="#cb17-20" tabindex="-1"></a>) <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">model =</span> <span class="st">&quot;B-spline (df 5)&quot;</span>)</span>
<span id="cb17-21"><a href="#cb17-21" tabindex="-1"></a></span>
<span id="cb17-22"><a href="#cb17-22" tabindex="-1"></a><span class="fu">bind_rows</span>(poly_lines, step_lines, spline_lines) <span class="sc">%&gt;%</span></span>
<span id="cb17-23"><a href="#cb17-23" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes_string</span>(<span class="at">x =</span> best_mech, <span class="at">y =</span> <span class="st">&quot;.pred&quot;</span>, <span class="at">colour =</span> <span class="st">&quot;model&quot;</span>)) <span class="sc">+</span></span>
<span id="cb17-24"><a href="#cb17-24" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb17-25"><a href="#cb17-25" tabindex="-1"></a>  <span class="fu">geom_ribbon</span>(<span class="fu">aes</span>(<span class="at">ymin =</span> .pred_lower, <span class="at">ymax =</span> .pred_upper, <span class="at">fill =</span> model),</span>
<span id="cb17-26"><a href="#cb17-26" tabindex="-1"></a>              <span class="at">alpha =</span> <span class="fl">0.1</span>, <span class="at">colour =</span> <span class="cn">NA</span>) <span class="sc">+</span></span>
<span id="cb17-27"><a href="#cb17-27" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> train_data,</span>
<span id="cb17-28"><a href="#cb17-28" tabindex="-1"></a>             <span class="fu">aes_string</span>(<span class="at">x =</span> best_mech, <span class="at">y =</span> <span class="st">&quot;pitch_speed_mph&quot;</span>),</span>
<span id="cb17-29"><a href="#cb17-29" tabindex="-1"></a>             <span class="at">alpha =</span> <span class="fl">0.15</span>, <span class="at">inherit.aes =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb17-30"><a href="#cb17-30" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="fu">paste0</span>(<span class="st">&quot;Non-linear fits for &quot;</span>, best_mech, <span class="st">&quot; vs. velocity&quot;</span>),</span>
<span id="cb17-31"><a href="#cb17-31" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;Predicted mph&quot;</span>, <span class="at">colour =</span> <span class="cn">NULL</span>, <span class="at">fill =</span> <span class="cn">NULL</span>) <span class="sc">+</span></span>
<span id="cb17-32"><a href="#cb17-32" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="FinalProject1_files/figure-html/poly-plot-1.png" width="672" style="display: block; margin: auto;" /></p>
</div>
<div id="optimal-range-for-variables" class="section level2"
number="6.3">
<h2><span class="header-section-number">6.3</span> Optimal range for
variables</h2>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" tabindex="-1"></a>opt_range <span class="ot">&lt;-</span> <span class="cf">function</span>(fitted_wflow,</span>
<span id="cb18-2"><a href="#cb18-2" tabindex="-1"></a>                      train_df,</span>
<span id="cb18-3"><a href="#cb18-3" tabindex="-1"></a>                      <span class="at">vars        =</span> <span class="cn">NULL</span>,</span>
<span id="cb18-4"><a href="#cb18-4" tabindex="-1"></a>                      <span class="at">mph_tol     =</span> <span class="fl">0.5</span>,</span>
<span id="cb18-5"><a href="#cb18-5" tabindex="-1"></a>                      <span class="at">grid_size   =</span> <span class="dv">50</span>) {</span>
<span id="cb18-6"><a href="#cb18-6" tabindex="-1"></a></span>
<span id="cb18-7"><a href="#cb18-7" tabindex="-1"></a>  rf_fit  <span class="ot">&lt;-</span> <span class="fu">extract_fit_parsnip</span>(fitted_wflow)</span>
<span id="cb18-8"><a href="#cb18-8" tabindex="-1"></a>  train_x <span class="ot">&lt;-</span> <span class="fu">bake</span>(</span>
<span id="cb18-9"><a href="#cb18-9" tabindex="-1"></a>    <span class="fu">extract_recipe</span>(fitted_wflow),</span>
<span id="cb18-10"><a href="#cb18-10" tabindex="-1"></a>    <span class="at">new_data =</span> train_df</span>
<span id="cb18-11"><a href="#cb18-11" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb18-12"><a href="#cb18-12" tabindex="-1"></a>    <span class="fu">select</span>(<span class="sc">-</span>pitch_speed_mph)</span>
<span id="cb18-13"><a href="#cb18-13" tabindex="-1"></a></span>
<span id="cb18-14"><a href="#cb18-14" tabindex="-1"></a>  <span class="cf">if</span> (<span class="fu">is.null</span>(vars)) {</span>
<span id="cb18-15"><a href="#cb18-15" tabindex="-1"></a>    vars <span class="ot">&lt;-</span> train_x <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="fu">where</span>(is.numeric)) <span class="sc">%&gt;%</span> <span class="fu">names</span>()</span>
<span id="cb18-16"><a href="#cb18-16" tabindex="-1"></a>  }</span>
<span id="cb18-17"><a href="#cb18-17" tabindex="-1"></a></span>
<span id="cb18-18"><a href="#cb18-18" tabindex="-1"></a>  <span class="fu">map_dfr</span>(vars, <span class="cf">function</span>(v) {</span>
<span id="cb18-19"><a href="#cb18-19" tabindex="-1"></a>    pd <span class="ot">&lt;-</span> <span class="fu">partial</span>(</span>
<span id="cb18-20"><a href="#cb18-20" tabindex="-1"></a>      rf_fit<span class="sc">$</span>fit,</span>
<span id="cb18-21"><a href="#cb18-21" tabindex="-1"></a>      <span class="at">pred.var        =</span> v,</span>
<span id="cb18-22"><a href="#cb18-22" tabindex="-1"></a>      <span class="at">train           =</span> train_x,</span>
<span id="cb18-23"><a href="#cb18-23" tabindex="-1"></a>      <span class="at">grid.resolution =</span> grid_size,</span>
<span id="cb18-24"><a href="#cb18-24" tabindex="-1"></a>      <span class="at">progress        =</span> <span class="st">&quot;none&quot;</span></span>
<span id="cb18-25"><a href="#cb18-25" tabindex="-1"></a>    )</span>
<span id="cb18-26"><a href="#cb18-26" tabindex="-1"></a></span>
<span id="cb18-27"><a href="#cb18-27" tabindex="-1"></a>    peak <span class="ot">&lt;-</span> <span class="fu">max</span>(pd<span class="sc">$</span>yhat, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb18-28"><a href="#cb18-28" tabindex="-1"></a></span>
<span id="cb18-29"><a href="#cb18-29" tabindex="-1"></a>    pd <span class="sc">%&gt;%</span></span>
<span id="cb18-30"><a href="#cb18-30" tabindex="-1"></a>      <span class="fu">filter</span>(yhat <span class="sc">&gt;=</span> peak <span class="sc">-</span> mph_tol) <span class="sc">%&gt;%</span></span>
<span id="cb18-31"><a href="#cb18-31" tabindex="-1"></a>      <span class="fu">summarise</span>(</span>
<span id="cb18-32"><a href="#cb18-32" tabindex="-1"></a>        <span class="at">variable =</span> v,</span>
<span id="cb18-33"><a href="#cb18-33" tabindex="-1"></a>        <span class="at">opt_min  =</span> <span class="fu">min</span>(.data[[v]], <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb18-34"><a href="#cb18-34" tabindex="-1"></a>        <span class="at">opt_max  =</span> <span class="fu">max</span>(.data[[v]], <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb18-35"><a href="#cb18-35" tabindex="-1"></a>      )</span>
<span id="cb18-36"><a href="#cb18-36" tabindex="-1"></a>  })</span>
<span id="cb18-37"><a href="#cb18-37" tabindex="-1"></a>}</span>
<span id="cb18-38"><a href="#cb18-38" tabindex="-1"></a></span>
<span id="cb18-39"><a href="#cb18-39" tabindex="-1"></a>vars_of_interest <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb18-40"><a href="#cb18-40" tabindex="-1"></a>  <span class="st">&quot;elbow_transfer_fp_br&quot;</span>,</span>
<span id="cb18-41"><a href="#cb18-41" tabindex="-1"></a>  <span class="st">&quot;max_shoulder_horizontal_abduction&quot;</span>,</span>
<span id="cb18-42"><a href="#cb18-42" tabindex="-1"></a>  <span class="st">&quot;torso_rotation_br&quot;</span>,</span>
<span id="cb18-43"><a href="#cb18-43" tabindex="-1"></a>  <span class="st">&quot;lead_knee_extension_from_fp_to_br&quot;</span>,</span>
<span id="cb18-44"><a href="#cb18-44" tabindex="-1"></a>  <span class="st">&quot;elbow_flexion_fp&quot;</span></span>
<span id="cb18-45"><a href="#cb18-45" tabindex="-1"></a>)</span>
<span id="cb18-46"><a href="#cb18-46" tabindex="-1"></a></span>
<span id="cb18-47"><a href="#cb18-47" tabindex="-1"></a>opt_tbl <span class="ot">&lt;-</span> <span class="fu">opt_range</span>(rf_final, train_data, <span class="at">vars =</span> vars_of_interest)</span>
<span id="cb18-48"><a href="#cb18-48" tabindex="-1"></a></span>
<span id="cb18-49"><a href="#cb18-49" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(</span>
<span id="cb18-50"><a href="#cb18-50" tabindex="-1"></a>  opt_tbl,</span>
<span id="cb18-51"><a href="#cb18-51" tabindex="-1"></a>  <span class="at">digits    =</span> <span class="dv">2</span>,</span>
<span id="cb18-52"><a href="#cb18-52" tabindex="-1"></a>  <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">&quot;Variable&quot;</span>, <span class="st">&quot;Optimal min&quot;</span>, <span class="st">&quot;Optimal max&quot;</span>)</span>
<span id="cb18-53"><a href="#cb18-53" tabindex="-1"></a>)</span></code></pre></div>
<table>
<thead>
<tr class="header">
<th align="left">Variable</th>
<th align="right">Optimal min</th>
<th align="right">Optimal max</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">elbow_transfer_fp_br</td>
<td align="right">318.56</td>
<td align="right">482.07</td>
</tr>
<tr class="even">
<td align="left">max_shoulder_horizontal_abduction</td>
<td align="right">30.46</td>
<td align="right">75.82</td>
</tr>
<tr class="odd">
<td align="left">torso_rotation_br</td>
<td align="right">93.69</td>
<td align="right">144.43</td>
</tr>
<tr class="even">
<td align="left">lead_knee_extension_from_fp_to_br</td>
<td align="right">-17.71</td>
<td align="right">55.19</td>
</tr>
<tr class="odd">
<td align="left">elbow_flexion_fp</td>
<td align="right">50.33</td>
<td align="right">137.98</td>
</tr>
</tbody>
</table>
<p>The table above shows the <strong>optimal mechanical ranges</strong>
that a pitcher should strive for, based on the random-forest
partial-dependence analysis. <code>elbow_transfer_fp_br</code> is
measured in joules; the other variables are measured in degrees (see
variable glossary in the EDA).</p>
</div>
</div>
<div id="conclusion" class="section level1" number="7">
<h1><span class="header-section-number">7</span> Conclusion</h1>
<div id="key-findings" class="section level2" number="7.1">
<h2><span class="header-section-number">7.1</span> Key findings</h2>
<ol style="list-style-type: decimal">
<li><strong>Model accuracy.</strong> The multivariate adaptive
regression splines (<strong>MARS</strong>) model captured <strong>90.8 %
of the variance</strong> in fastball speed on five-fold cross-validation
($R^{2}=0.908$), outperforming the tuned random-forest (≈ 84 %).</li>
<li><strong>Quick wins for velo.</strong> Across every model, the
steepest positive partial-dependence slopes belonged to <strong>shoulder
external rotation (ER)</strong> and <strong>elbow ER</strong> during
late cocking / early acceleration. A 5–10 ° shift toward each joint’s
optimal band predicts ≈ 0.6–0.9 mph gains.</li>
<li><strong>Engine building over time.</strong> Hard throwers also
exhibit higher joint angular velocities, implying that <strong>improving
fast-twitch fibre recruitment</strong> (plyometrics, speed training, and
lifting) will keep raising the ceiling once mechanical ranges are
optimised.</li>
</ol>
</div>
<div id="practical-guidelines" class="section level2" number="7.2">
<h2><span class="header-section-number">7.2</span> Practical
guidelines</h2>
<table>
<colgroup>
<col width="24%" />
<col width="29%" />
<col width="46%" />
</colgroup>
<thead>
<tr class="header">
<th>Focus area</th>
<th>What to monitor</th>
<th>Suggested cue / drill</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Shoulder ER (late cocking)</td>
<td>Lay-back ≈ 175°–190°</td>
<td>Weighted-ball reverse throws; seated wall ER</td>
</tr>
<tr class="even">
<td>Elbow ER</td>
<td>Forearm-to-humerus angle ≥ 110°</td>
<td>“Figure-eight” plyo routine</td>
</tr>
<tr class="odd">
<td>Quick-twitch power</td>
<td>Peak angular-velocity trend</td>
<td>Med-ball scoop-toss to radar; clean-pull velocity</td>
</tr>
</tbody>
</table>
</div>
<div id="limitations" class="section level2" number="7.3">
<h2><span class="header-section-number">7.3</span> Limitations</h2>
<ul>
<li><strong>Sample size &amp; scope.</strong> ≈ 2 000 pitches from ~100
high-level throwers; youth and HS mechanics remain
under-represented.</li>
<li><strong>Athlete context.</strong> Dataset lacks <strong>baseline
strength metrics</strong> (e.g., 1RM, vertical jump) that mediate
mechanical efficiency.</li>
<li><strong>Single-session snapshots.</strong> No longitudinal
tracking—cannot separate innate traits from training adaptations.</li>
</ul>
</div>
<div id="future-research-directions" class="section level2"
number="7.4">
<h2><span class="header-section-number">7.4</span> Future research
directions</h2>
<ul>
<li><strong>Augment metadata</strong> with pitcher weight, strength
scores, pitch counts, and training history to normalise for athlete
capacity.</li>
<li><strong>Validate optimal-range tables</strong> in live bullpens: do
pitchers who migrate toward our recommended bands gain velocity without
elevated joint torques?</li>
</ul>
</div>
</div>
<div id="ai-reflective-statement" class="section level1" number="8">
<h1><span class="header-section-number">8</span> AI reflective
statement</h1>
<p>I used AI for a couple of different things in this project. Although
most of the code for the regression models that I used was from class
activities, I was getting errors that I couldn’t find the solution to. I
used chatGPT to help resolve the error in the recipe. I was not familiar
with how to code the part for finding the best ranges for the different
pitch mechanics and chatGPT was able to help me with exactly what I was
wanting to accomplish with this part of the project. I also used AI to
help me format the final draft. This included getting the format so the
r markdown was written in a way that it would be easy to read when
knitted to html as well as editing any grammatical mistakes in the
writing. I finally used AI to help me with the plot in the results
secton for comparing the different regression models. Overall, I thought
that AI was very helpful in assisting my project. I would say that I
felt very comfortable with understanding the data with it being about
baseball, meaning that any code for models and plots that AI could help
me with, I would have an understanding of if the results made sense in
the context of the data. For that reason I felt comfortable using it,
but if it were data that I was less familar with, I would have been more
careful with it for sure.</p>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
